name: visitor_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  http: ^0.13.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  dots_indicator: ^3.0.0
  lottie: ^2.3.2

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/app_logo.png"
 

flutter: 
  uses-material-design: true

  assets:
    - assets/image/
    - assets/font/
    - assets/file/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900

-material-design: true
